export default () => ({
  countries: [
    {
      id: 1,
      code: 'AF',
      name: 'Afghanistan',
    },
    {
      id: 2,
      code: 'AX',
      name: 'Aland Islands',
    },
    {
      id: 3,
      code: 'AL',
      name: 'Albania',
    },
    {
      id: 4,
      code: 'DZ',
      name: 'Algeria',
    },
    {
      id: 5,
      code: 'AS',
      name: 'American Samoa',
    },
    {
      id: 6,
      code: 'AD',
      name: 'Andorra',
    },
    {
      id: 7,
      code: 'AO',
      name: 'Angola',
    },
    {
      id: 8,
      code: 'AI',
      name: 'Anguilla',
    },
    {
      id: 9,
      code: 'AQ',
      name: 'Antarctica',
    },
    {
      id: 10,
      code: 'AG',
      name: 'Antigua and Barbuda',
    },
    {
      id: 11,
      code: 'AR',
      name: 'Argentina',
    },
    {
      id: 12,
      code: 'AM',
      name: 'Armenia',
    },
    {
      id: 13,
      code: 'AW',
      name: 'Aruba',
    },
    {
      id: 14,
      code: 'AU',
      name: 'Australia',
    },
    {
      id: 15,
      code: 'AT',
      name: 'Austria',
    },
    {
      id: 16,
      code: 'AZ',
      name: 'Azerbaijan',
    },
    {
      id: 17,
      code: 'BS',
      name: 'Bahamas',
    },
    {
      id: 18,
      code: 'BH',
      name: 'Bahrain',
    },
    {
      id: 19,
      code: 'BD',
      name: 'Bangladesh',
    },
    {
      id: 20,
      code: 'BB',
      name: 'Barbados',
    },
    {
      id: 21,
      code: 'BY',
      name: 'Belarus',
    },
    {
      id: 22,
      code: 'BE',
      name: 'Belgium',
    },
    {
      id: 23,
      code: 'BZ',
      name: 'Belize',
    },
    {
      id: 24,
      code: 'BJ',
      name: 'Benin',
    },
    {
      id: 25,
      code: 'BM',
      name: 'Bermuda',
    },
    {
      id: 26,
      code: 'BT',
      name: 'Bhutan',
    },
    {
      id: 27,
      code: 'BO',
      name: 'Bolivia, Plurinational State of',
    },
    {
      id: 28,
      code: 'BQ',
      name: 'Bonaire, Sint Eustatius and Saba',
    },
    {
      id: 29,
      code: 'BA',
      name: 'Bosnia and Herzegovina',
    },
    {
      id: 30,
      code: 'BW',
      name: 'Botswana',
    },
    {
      id: 31,
      code: 'BV',
      name: 'Bouvet Island',
    },
    {
      id: 32,
      code: 'BR',
      name: 'Brazil',
    },
    {
      id: 33,
      code: 'IO',
      name: 'British Indian Ocean Territory',
    },
    {
      id: 34,
      code: 'BN',
      name: 'Brunei Darussalam',
    },
    {
      id: 35,
      code: 'BG',
      name: 'Bulgaria',
    },
    {
      id: 36,
      code: 'BF',
      name: 'Burkina Faso',
    },
    {
      id: 37,
      code: 'BI',
      name: 'Burundi',
    },
    {
      id: 38,
      code: 'KH',
      name: 'Cambodia',
    },
    {
      id: 39,
      code: 'CM',
      name: 'Cameroon',
    },
    {
      id: 40,
      code: 'CA',
      name: 'Canada',
    },
    {
      id: 41,
      code: 'CV',
      name: 'Cape Verde',
    },
    {
      id: 42,
      code: 'KY',
      name: 'Cayman Islands',
    },
    {
      id: 43,
      code: 'CF',
      name: 'Central African Republic',
    },
    {
      id: 44,
      code: 'TD',
      name: 'Chad',
    },
    {
      id: 45,
      code: 'CL',
      name: 'Chile',
    },
    {
      id: 46,
      code: 'CN',
      name: 'China',
    },
    {
      id: 47,
      code: 'CX',
      name: 'Christmas Island',
    },
    {
      id: 48,
      code: 'CC',
      name: 'Cocos (Keeling) Islands',
    },
    {
      id: 49,
      code: 'CO',
      name: 'Colombia',
    },
    {
      id: 50,
      code: 'KM',
      name: 'Comoros',
    },
    {
      id: 51,
      code: 'CG',
      name: 'Congo',
    },
    {
      id: 52,
      code: 'CD',
      name: 'Congo, the Democratic Republic of the',
    },
    {
      id: 53,
      code: 'CK',
      name: 'Cook Islands',
    },
    {
      id: 54,
      code: 'CR',
      name: 'Costa Rica',
    },
    {
      id: 55,
      code: 'CI',
      name: "C\u00F4te d'Ivoire",
    },
    {
      id: 56,
      code: 'HR',
      name: 'Croatia',
    },
    {
      id: 57,
      code: 'CU',
      name: 'Cuba',
    },
    {
      id: 58,
      code: 'CW',
      name: 'Cura\u00E7ao',
    },
    {
      id: 59,
      code: 'CY',
      name: 'Cyprus',
    },
    {
      id: 60,
      code: 'CZ',
      name: 'Czech Republic',
    },
    {
      id: 61,
      code: 'DK',
      name: 'Denmark',
    },
    {
      id: 62,
      code: 'DJ',
      name: 'Djibouti',
    },
    {
      id: 63,
      code: 'DM',
      name: 'Dominica',
    },
    {
      id: 64,
      code: 'DO',
      name: 'Dominican Republic',
    },
    {
      id: 65,
      code: 'EC',
      name: 'Ecuador',
    },
    {
      id: 66,
      code: 'EG',
      name: 'Egypt',
    },
    {
      id: 67,
      code: 'SV',
      name: 'El Salvador',
    },
    {
      id: 68,
      code: 'GQ',
      name: 'Equatorial Guinea',
    },
    {
      id: 69,
      code: 'ER',
      name: 'Eritrea',
    },
    {
      id: 70,
      code: 'EE',
      name: 'Estonia',
    },
    {
      id: 71,
      code: 'ET',
      name: 'Ethiopia',
    },
    {
      id: 72,
      code: 'FK',
      name: 'Falkland Islands (Malvinas)',
    },
    {
      id: 73,
      code: 'FO',
      name: 'Faroe Islands',
    },
    {
      id: 74,
      code: 'FJ',
      name: 'Fiji',
    },
    {
      id: 75,
      code: 'FI',
      name: 'Finland',
    },
    {
      id: 76,
      code: 'FR',
      name: 'France',
    },
    {
      id: 77,
      code: 'GF',
      name: 'French Guiana',
    },
    {
      id: 78,
      code: 'PF',
      name: 'French Polynesia',
    },
    {
      id: 79,
      code: 'TF',
      name: 'French Southern Territories',
    },
    {
      id: 80,
      code: 'GA',
      name: 'Gabon',
    },
    {
      id: 81,
      code: 'GM',
      name: 'Gambia',
    },
    {
      id: 82,
      code: 'GE',
      name: 'Georgia',
    },
    {
      id: 83,
      code: 'DE',
      name: 'Germany',
    },
    {
      id: 84,
      code: 'GH',
      name: 'Ghana',
    },
    {
      id: 85,
      code: 'GI',
      name: 'Gibraltar',
    },
    {
      id: 86,
      code: 'GR',
      name: 'Greece',
    },
    {
      id: 87,
      code: 'GL',
      name: 'Greenland',
    },
    {
      id: 88,
      code: 'GD',
      name: 'Grenada',
    },
    {
      id: 89,
      code: 'GP',
      name: 'Guadeloupe',
    },
    {
      id: 90,
      code: 'GU',
      name: 'Guam',
    },
    {
      id: 91,
      code: 'GT',
      name: 'Guatemala',
    },
    {
      id: 92,
      code: 'GG',
      name: 'Guernsey',
    },
    {
      id: 93,
      code: 'GN',
      name: 'Guinea',
    },
    {
      id: 94,
      code: 'GW',
      name: 'Guinea-Bissau',
    },
    {
      id: 95,
      code: 'GY',
      name: 'Guyana',
    },
    {
      id: 96,
      code: 'HT',
      name: 'Haiti',
    },
    {
      id: 97,
      code: 'HM',
      name: 'Heard Island and McDonald Islands',
    },
    {
      id: 98,
      code: 'VA',
      name: 'Holy See (Vatican City State)',
    },
    {
      id: 99,
      code: 'HN',
      name: 'Honduras',
    },
    {
      id: 100,
      code: 'HK',
      name: 'Hong Kong, China',
    },
    {
      id: 101,
      code: 'HU',
      name: 'Hungary',
    },
    {
      id: 102,
      code: 'IS',
      name: 'Iceland',
    },
    {
      id: 103,
      code: 'IN',
      name: 'India',
    },
    {
      id: 104,
      code: 'ID',
      name: 'Indonesia',
    },
    {
      id: 105,
      code: 'IR',
      name: 'Iran, Islamic Republic of',
    },
    {
      id: 106,
      code: 'IQ',
      name: 'Iraq',
    },
    {
      id: 107,
      code: 'IE',
      name: 'Ireland',
    },
    {
      id: 108,
      code: 'IM',
      name: 'Isle of Man',
    },
    {
      id: 109,
      code: 'IL',
      name: 'Israel',
    },
    {
      id: 110,
      code: 'IT',
      name: 'Italy',
    },
    {
      id: 111,
      code: 'JM',
      name: 'Jamaica',
    },
    {
      id: 112,
      code: 'JP',
      name: 'Japan',
    },
    {
      id: 113,
      code: 'JE',
      name: 'Jersey',
    },
    {
      id: 114,
      code: 'JO',
      name: 'Jordan',
    },
    {
      id: 115,
      code: 'KZ',
      name: 'Kazakhstan',
    },
    {
      id: 116,
      code: 'KE',
      name: 'Kenya',
    },
    {
      id: 117,
      code: 'KI',
      name: 'Kiribati',
    },
    {
      id: 118,
      code: 'KP',
      name: "Korea, Democratic People's Republic of",
    },
    {
      id: 119,
      code: 'KR',
      name: 'Korea, Republic of',
    },
    {
      id: 120,
      code: 'KW',
      name: 'Kuwait',
    },
    {
      id: 121,
      code: 'KG',
      name: 'Kyrgyzstan',
    },
    {
      id: 122,
      code: 'LA',
      name: "Lao People's Democratic Republic",
    },
    {
      id: 123,
      code: 'LV',
      name: 'Latvia',
    },
    {
      id: 124,
      code: 'LB',
      name: 'Lebanon',
    },
    {
      id: 125,
      code: 'LS',
      name: 'Lesotho',
    },
    {
      id: 126,
      code: 'LR',
      name: 'Liberia',
    },
    {
      id: 127,
      code: 'LY',
      name: 'Libya',
    },
    {
      id: 128,
      code: 'LI',
      name: 'Liechtenstein',
    },
    {
      id: 129,
      code: 'LT',
      name: 'Lithuania',
    },
    {
      id: 130,
      code: 'LU',
      name: 'Luxembourg',
    },
    {
      id: 131,
      code: 'MO',
      name: 'Macao, China',
    },
    {
      id: 132,
      code: 'MK',
      name: 'Macedonia, the Former Yugoslav Republic of',
    },
    {
      id: 133,
      code: 'MG',
      name: 'Madagascar',
    },
    {
      id: 134,
      code: 'MW',
      name: 'Malawi',
    },
    {
      id: 135,
      code: 'MY',
      name: 'Malaysia',
    },
    {
      id: 136,
      code: 'MV',
      name: 'Maldives',
    },
    {
      id: 137,
      code: 'ML',
      name: 'Mali',
    },
    {
      id: 138,
      code: 'MT',
      name: 'Malta',
    },
    {
      id: 139,
      code: 'MH',
      name: 'Marshall Islands',
    },
    {
      id: 140,
      code: 'MQ',
      name: 'Martinique',
    },
    {
      id: 141,
      code: 'MR',
      name: 'Mauritania',
    },
    {
      id: 142,
      code: 'MU',
      name: 'Mauritius',
    },
    {
      id: 143,
      code: 'YT',
      name: 'Mayotte',
    },
    {
      id: 144,
      code: 'MX',
      name: 'Mexico',
    },
    {
      id: 145,
      code: 'FM',
      name: 'Micronesia, Federated States of',
    },
    {
      id: 146,
      code: 'MD',
      name: 'Moldova, Republic of',
    },
    {
      id: 147,
      code: 'MC',
      name: 'Monaco',
    },
    {
      id: 148,
      code: 'MN',
      name: 'Mongolia',
    },
    {
      id: 149,
      code: 'ME',
      name: 'Montenegro',
    },
    {
      id: 150,
      code: 'MS',
      name: 'Montserrat',
    },
    {
      id: 151,
      code: 'MA',
      name: 'Morocco',
    },
    {
      id: 152,
      code: 'MZ',
      name: 'Mozambique',
    },
    {
      id: 153,
      code: 'MM',
      name: 'Myanmar',
    },
    {
      id: 154,
      code: 'NA',
      name: 'Namibia',
    },
    {
      id: 155,
      code: 'NR',
      name: 'Nauru',
    },
    {
      id: 156,
      code: 'NP',
      name: 'Nepal',
    },
    {
      id: 157,
      code: 'NL',
      name: 'Netherlands',
    },
    {
      id: 158,
      code: 'NC',
      name: 'New Caledonia',
    },
    {
      id: 159,
      code: 'NZ',
      name: 'New Zealand',
    },
    {
      id: 160,
      code: 'NI',
      name: 'Nicaragua',
    },
    {
      id: 161,
      code: 'NE',
      name: 'Niger',
    },
    {
      id: 162,
      code: 'NG',
      name: 'Nigeria',
    },
    {
      id: 163,
      code: 'NU',
      name: 'Niue',
    },
    {
      id: 164,
      code: 'NF',
      name: 'Norfolk Island',
    },
    {
      id: 165,
      code: 'MP',
      name: 'Northern Mariana Islands',
    },
    {
      id: 166,
      code: 'NO',
      name: 'Norway',
    },
    {
      id: 167,
      code: 'OM',
      name: 'Oman',
    },
    {
      id: 168,
      code: 'PK',
      name: 'Pakistan',
    },
    {
      id: 169,
      code: 'PW',
      name: 'Palau',
    },
    {
      id: 170,
      code: 'PS',
      name: 'Palestine, State of',
    },
    {
      id: 171,
      code: 'PA',
      name: 'Panama',
    },
    {
      id: 172,
      code: 'PG',
      name: 'Papua New Guinea',
    },
    {
      id: 173,
      code: 'PY',
      name: 'Paraguay',
    },
    {
      id: 174,
      code: 'PE',
      name: 'Peru',
    },
    {
      id: 175,
      code: 'PH',
      name: 'Philippines',
    },
    {
      id: 176,
      code: 'PN',
      name: 'Pitcairn',
    },
    {
      id: 177,
      code: 'PL',
      name: 'Poland',
    },
    {
      id: 178,
      code: 'PT',
      name: 'Portugal',
    },
    {
      id: 179,
      code: 'PR',
      name: 'Puerto Rico',
    },
    {
      id: 180,
      code: 'QA',
      name: 'Qatar',
    },
    {
      id: 181,
      code: 'RE',
      name: 'R\u00E9union',
    },
    {
      id: 182,
      code: 'RO',
      name: 'Romania',
    },
    {
      id: 183,
      code: 'RU',
      name: 'Russian Federation',
    },
    {
      id: 184,
      code: 'RW',
      name: 'Rwanda',
    },
    {
      id: 185,
      code: 'BL',
      name: 'Saint Barth\u00E9lemy',
    },
    {
      id: 186,
      code: 'SH',
      name: 'Saint Helena, Ascension and Tristan da Cunha',
    },
    {
      id: 187,
      code: 'KN',
      name: 'Saint Kitts and Nevis',
    },
    {
      id: 188,
      code: 'LC',
      name: 'Saint Lucia',
    },
    {
      id: 189,
      code: 'MF',
      name: 'Saint Martin (French part)',
    },
    {
      id: 190,
      code: 'PM',
      name: 'Saint Pierre and Miquelon',
    },
    {
      id: 191,
      code: 'VC',
      name: 'Saint Vincent and the Grenadines',
    },
    {
      id: 192,
      code: 'WS',
      name: 'Samoa',
    },
    {
      id: 193,
      code: 'SM',
      name: 'San Marino',
    },
    {
      id: 194,
      code: 'ST',
      name: 'Sao Tome and Principe',
    },
    {
      id: 195,
      code: 'SA',
      name: 'Saudi Arabia',
    },
    {
      id: 196,
      code: 'SN',
      name: 'Senegal',
    },
    {
      id: 197,
      code: 'RS',
      name: 'Serbia',
    },
    {
      id: 198,
      code: 'SC',
      name: 'Seychelles',
    },
    {
      id: 199,
      code: 'SL',
      name: 'Sierra Leone',
    },
    {
      id: 200,
      code: 'SG',
      name: 'Singapore',
    },
    {
      id: 201,
      code: 'SX',
      name: 'Sint Maarten (Dutch part)',
    },
    {
      id: 202,
      code: 'SK',
      name: 'Slovakia',
    },
    {
      id: 203,
      code: 'SI',
      name: 'Slovenia',
    },
    {
      id: 204,
      code: 'SB',
      name: 'Solomon Islands',
    },
    {
      id: 205,
      code: 'SO',
      name: 'Somalia',
    },
    {
      id: 206,
      code: 'ZA',
      name: 'South Africa',
    },
    {
      id: 207,
      code: 'GS',
      name: 'South Georgia and the South Sandwich Islands',
    },
    {
      id: 208,
      code: 'SS',
      name: 'South Sudan',
    },
    {
      id: 209,
      code: 'ES',
      name: 'Spain',
    },
    {
      id: 210,
      code: 'LK',
      name: 'Sri Lanka',
    },
    {
      id: 211,
      code: 'SD',
      name: 'Sudan',
    },
    {
      id: 212,
      code: 'SR',
      name: 'Suriname',
    },
    {
      id: 213,
      code: 'SJ',
      name: 'Svalbard and Jan Mayen',
    },
    {
      id: 214,
      code: 'SZ',
      name: 'Swaziland',
    },
    {
      id: 215,
      code: 'SE',
      name: 'Sweden',
    },
    {
      id: 216,
      code: 'CH',
      name: 'Switzerland',
    },
    {
      id: 217,
      code: 'SY',
      name: 'Syrian Arab Republic',
    },
    {
      id: 218,
      code: 'TW',
      name: 'Taiwan, China',
    },
    {
      id: 219,
      code: 'TJ',
      name: 'Tajikistan',
    },
    {
      id: 220,
      code: 'TZ',
      name: 'Tanzania, United Republic of',
    },
    {
      id: 221,
      code: 'TH',
      name: 'Thailand',
    },
    {
      id: 222,
      code: 'TL',
      name: 'Timor-Leste',
    },
    {
      id: 223,
      code: 'TG',
      name: 'Togo',
    },
    {
      id: 224,
      code: 'TK',
      name: 'Tokelau',
    },
    {
      id: 225,
      code: 'TO',
      name: 'Tonga',
    },
    {
      id: 226,
      code: 'TT',
      name: 'Trinidad and Tobago',
    },
    {
      id: 227,
      code: 'TN',
      name: 'Tunisia',
    },
    {
      id: 228,
      code: 'TR',
      name: 'Turkey',
    },
    {
      id: 229,
      code: 'TM',
      name: 'Turkmenistan',
    },
    {
      id: 230,
      code: 'TC',
      name: 'Turks and Caicos Islands',
    },
    {
      id: 231,
      code: 'TV',
      name: 'Tuvalu',
    },
    {
      id: 232,
      code: 'UG',
      name: 'Uganda',
    },
    {
      id: 233,
      code: 'UA',
      name: 'Ukraine',
    },
    {
      id: 234,
      code: 'AE',
      name: 'United Arab Emirates',
    },
    {
      id: 235,
      code: 'GB',
      name: 'United Kingdom',
    },
    {
      id: 236,
      code: 'US',
      name: 'United States',
    },
    {
      id: 237,
      code: 'UM',
      name: 'United States Minor Outlying Islands',
    },
    {
      id: 238,
      code: 'UY',
      name: 'Uruguay',
    },
    {
      id: 239,
      code: 'UZ',
      name: 'Uzbekistan',
    },
    {
      id: 240,
      code: 'VU',
      name: 'Vanuatu',
    },
    {
      id: 241,
      code: 'VE',
      name: 'Venezuela, Bolivarian Republic of',
    },
    {
      id: 242,
      code: 'VN',
      name: 'Viet Nam',
    },
    {
      id: 243,
      code: 'VG',
      name: 'Virgin Islands, British',
    },
    {
      id: 244,
      code: 'VI',
      name: 'Virgin Islands, U.S.',
    },
    {
      id: 245,
      code: 'WF',
      name: 'Wallis and Futuna',
    },
    {
      id: 246,
      code: 'EH',
      name: 'Western Sahara',
    },
    {
      id: 247,
      code: 'YE',
      name: 'Yemen',
    },
    {
      id: 248,
      code: 'ZM',
      name: 'Zambia',
    },
    {
      id: 249,
      code: 'ZW',
      name: 'Zimbabwe',
    },
  ],
  states: {
    AE: {
      AE: 'AE',
    },
    AR: {
      0: 'Capital Federal',
      1: 'Buenos Aires',
      2: 'Catamarca',
      3: 'Córdoba',
      4: 'Corrientes',
      5: 'Entre Rios',
      6: 'Jujuy',
      7: 'Mendoza',
      8: 'La Rioja',
      9: 'Salta',
      10: 'San Juan',
      11: 'San Luis',
      12: 'Santa Fé',
      13: 'Santiago del Estero',
      14: 'Tucumán',
      16: 'Chaco',
      17: 'Chubut',
      18: 'Formosa',
      19: 'Misiones',
      20: 'Neuquen',
      21: 'La Pampa',
      22: 'Rio Negro',
      23: 'Santa Cruz',
      24: 'Tierra de Fuego',
    },
    AT: {
      B: 'Burgenland',
      K: 'Carinthia',
      NÖ: 'Lower Austria',
      OÖ: 'Upper Austria',
      S: 'Salzburg',
      ST: 'Styria',
      T: 'Tyrol',
      V: 'Vorarlberg',
      W: 'Vienna',
    },
    AU: {
      ACT: 'Aust Capital Terr',
      NSW: 'New South Wales',
      NT: 'Northern Territory',
      QLD: 'Queensland',
      SA: 'South Australia',
      TAS: 'Tasmania',
      VIC: 'Victoria',
      WA: 'Western Australia',
    },
    BE: {
      1: 'Antwerp',
      2: 'Brabant (Flemish)',
      3: 'Hainaut',
      4: 'Liege',
      5: 'Limburg',
      6: 'Luxembourg',
      7: 'Namur',
      8: 'Oost-Vlaanderen',
      9: 'West-Vlaanderen',
      10: 'Brabant (Walloon)',
      11: 'Brussels (Capital)',
    },
    BG: {
      1: 'Burgas',
      2: 'Grad Sofiya',
      3: 'Khaskovo',
      4: 'Lovech',
      5: 'Montana',
      6: 'Plovdiv',
      7: 'Ruse',
      8: 'Sofiya',
      9: 'Varna',
    },
    BR: {
      AC: 'Acre',
      AL: 'Alagoas',
      AM: 'Amazon',
      AP: 'Amapá',
      BA: 'Bahia',
      CE: 'Ceará',
      DF: 'Brasília',
      ES: 'Espírito Santo',
      GO: 'Goiás',
      MA: 'Maranhão',
      MG: 'Minas Gerais',
      MS: 'Mato Grosso do Sul',
      MT: 'Mato Grosso',
      PA: 'Pará',
      PB: 'Paraíba',
      PE: 'Pernambuco',
      PI: 'Piauí',
      PR: 'Paraná',
      RJ: 'Rio de Janeiro',
      RN: 'Rio Grande do Norte',
      RO: 'Rondônia',
      RR: 'Roraima',
      RS: 'Rio Grande do Sul',
      SC: 'Santa Catarina',
      SE: 'Sergipe',
      SP: 'São Paulo',
      TO: 'Tocantins',
    },
    CA: {
      AB: 'Alberta',
      BC: 'British Columbia',
      MB: 'Manitoba',
      NB: 'New Brunswick',
      NL: 'Newfoundland & Labr.',
      NS: 'Nova Scotia',
      NT: 'Northwest Terr.',
      NU: 'Nunavut',
      ON: 'Ontario',
      PE: 'Prince Edward Island',
      QC: 'Quebec',
      SK: 'Saskatchewan',
      YT: 'Yukon Territory',
    },
    CH: {
      AG: 'Aargau',
      AI: 'Inner-Rhoden',
      AR: 'Ausser-Rhoden',
      BE: 'Bern',
      BL: 'Basel Land',
      BS: 'Basel Stadt',
      FR: 'Fribourg',
      GE: 'Geneva',
      GL: 'Glarus',
      GR: 'Graubuenden',
      JU: 'Jura',
      LU: 'Lucerne',
      NE: 'Neuchatel',
      NW: 'Nidwalden',
      OW: 'Obwalden',
      SG: 'St. Gallen',
      SH: 'Schaffhausen',
      SO: 'Solothurn',
      SZ: 'Schwyz',
      TG: 'Thurgau',
      TI: 'Ticino',
      UR: 'Uri',
      VD: 'Vaud',
      VS: 'Valais',
      ZG: 'Zug',
      ZH: 'Zurich',
    },
    CL: {
      1: 'I - Iquique',
      2: 'II - Antofagasta',
      3: 'III - Copiapo',
      4: 'IV - La Serena',
      5: 'V - Valparaiso',
      6: 'VI - Rancagua',
      7: 'VII - Talca',
      8: 'VIII - Concepción',
      9: 'IX - Temuco',
      10: 'X - Puerto Montt',
      11: 'XI - Coyhaique',
      12: 'XII - Punta Arenas',
      13: 'RM - Santiago',
    },
    CN: {
      100: 'Jiangsu',
      110: 'Anhui',
      120: 'Shandong',
      130: 'Zhejiang',
      140: 'Jiangxi',
      150: 'Fujian',
      160: 'Hunan',
      170: 'Hubei',
      180: 'Henan',
      190: 'Guangdong',
      200: 'Hainan',
      210: 'Guangxi',
      220: 'Guizhou',
      230: 'Sichuan',
      240: 'Yunnan',
      250: 'Shaanxi',
      260: 'Gansu',
      270: 'Ningxia',
      280: 'Qinghai',
      290: 'Xinjiang',
      300: 'Xizang',
      320: 'Chongqing',
      10: 'Beijing',
      20: 'Shanghai',
      30: 'Tianjin',
      40: 'Nei Mongol',
      50: 'Shanxi',
      60: 'Hebei',
      70: 'Liaoning',
      80: 'Jilin',
      90: 'Heilongjiang',
    },
    CO: {
      5: 'ANTIOQUIA',
      8: 'ATLANTICO',
      11: 'BOGOTA',
      13: 'BOLIVAR',
      15: 'BOYACA',
      17: 'CALDAS',
      18: 'CAQUETA',
      19: 'CAUCA',
      20: 'CESAR',
      23: 'CORDOBA',
      25: 'CUNDINAMARCA',
      27: 'CHOCO',
      41: 'HUILA',
      44: 'LA GUAJIRA',
      47: 'MAGDALENA',
      50: 'META',
      52: 'NARIÑO',
      54: 'NORTE SANTANDER',
      63: 'QUINDIO',
      66: 'RISARALDA',
      68: 'SANTANDER',
      70: 'SUCRE',
      73: 'TOLIMA',
      76: 'VALLE',
      81: 'ARAUCA',
      85: 'CASANARE',
      86: 'PUTUMAYO',
      88: 'SAN ANDRES',
      91: 'AMAZONAS',
      94: 'GUAINIA',
      95: 'GUAVIARE',
      97: 'VAUPES',
      99: 'VICHADA',
    },
    CU: {
      14: 'Guantanamo',
    },
    CZ: {
      1: 'Jihocesky',
      2: 'Jihomoravsky',
      3: 'Praha',
      4: 'Severocesky',
      5: 'Severomoravsky',
      6: 'Stredocesky',
      7: 'Vychodocesky',
      8: 'Zapadocesky',
    },
    DE: {
      1: 'Schleswig-Holstein',
      2: 'Hamburg',
      3: 'Lower Saxony',
      4: 'Bremen',
      5: 'Nrth Rhine Westfalia',
      6: 'Hesse',
      7: 'Rhineland Palatinate',
      8: 'Baden-Wurttemberg',
      9: 'Bavaria',
      10: 'Saarland',
      11: 'Berlin',
      12: 'Brandenburg',
      13: 'Mecklenburg-Vorpomm.',
      14: 'Saxony',
      15: 'Saxony-Anhalt',
      16: 'Thuringia',
    },
    DK: {
      1: 'Region of Copenhagen',
      2: 'Central Denmark Region',
      3: 'North Denmark Region',
      4: 'Region of Southern Denmark',
      5: 'Region Zealand',
    },
    ES: {
      1: 'Alava',
      2: 'Albacete',
      3: 'Alicante',
      4: 'Almeria',
      5: 'Avila',
      6: 'Badajoz',
      7: 'Baleares',
      8: 'Barcelona',
      9: 'Burgos',
      10: 'Caceres',
      11: 'Cadiz',
      12: 'Castellon',
      13: 'Ciudad Real',
      14: 'Córdoba',
      15: 'La Coruña',
      16: 'Cuenca',
      17: 'Gerona',
      18: 'Granada',
      19: 'Guadalajara',
      20: 'Guipuzcoa',
      21: 'Huelva',
      22: 'Huesca',
      23: 'Jaen',
      24: 'León',
      25: 'Lerida',
      26: 'La Rioja',
      27: 'Lugo',
      28: 'Madrid',
      29: 'Malaga',
      30: 'Murcia',
      31: 'Navarra',
      32: 'Orense',
      33: 'Asturias',
      34: 'Palencia',
      35: 'Las Palmas',
      36: 'Pontevedra',
      37: 'Salamanca',
      38: 'Sta. Cruz Tenerife',
      39: 'Cantabria',
      40: 'Segovia',
      41: 'Sevilla',
      42: 'Soria',
      43: 'Tarragona',
      44: 'Teruel',
      45: 'Toledo',
      46: 'Valencia',
      47: 'Valladolid',
      48: 'Vizcaya',
      49: 'Zamora',
      50: 'Zaragoza',
    },
    FI: {
      1: 'Ahvenanmaa',
      2: 'Etelä-Suomi',
      3: 'Itä-Suomi',
      4: 'Lappi',
      5: 'Länsi-Suomi',
      6: 'Oulu',
    },
    FR: {
      971: 'Guadeloupe',
      972: 'Martinique',
      973: 'Guyane',
      974: 'Réunion',
      975: 'Saint-Pierre-et-Miq.',
      976: 'Wallis-et-Futuna',
      1: 'Ain',
      2: 'Aisne',
      3: 'Allier',
      4: 'Alpes (Hte-Provence)',
      5: 'Alpes (Hautes)',
      6: 'Alpes-Maritimes',
      7: 'Ardèche',
      8: 'Ardennes',
      9: 'Ariège',
      10: 'Aube',
      11: 'Aude',
      12: 'Aveyron',
      13: 'Bouches-du-Rhône',
      14: 'Calvados',
      15: 'Cantal',
      16: 'Charente',
      17: 'Charente-Maritime',
      18: 'Cher',
      19: 'Corrèze',
      21: "Côte-d'Or",
      22: "Côtes-d'Armor",
      23: 'Creuse',
      24: 'Dordogne',
      25: 'Doubs',
      26: 'Drôme',
      27: 'Eure',
      28: 'Eure-et-Loir',
      29: 'Finistère',
      '2A': 'Corse-du-Sud',
      '2B': 'Corse-du-Nord',
      30: 'Gard',
      31: 'Garonne (Haute)',
      32: 'Gers',
      33: 'Gironde',
      34: 'Hérault',
      35: 'Ille-et-Vilaine',
      36: 'Indre',
      37: 'Indre-et-Loire',
      38: 'Isère',
      39: 'Jura',
      40: 'Landes',
      41: 'Loir-et-Cher',
      42: 'Loire',
      43: 'Loire (Haute)',
      44: 'Loire-Atlantique',
      45: 'Loiret',
      46: 'Lot',
      47: 'Lot-et-Garonne',
      48: 'Lozère',
      49: 'Maine-et-Loire',
      50: 'Manche',
      51: 'Marne',
      52: 'Marne (Haute)',
      53: 'Mayenne',
      54: 'Meurthe-et-Moselle',
      55: 'Meuse',
      56: 'Morbihan',
      57: 'Moselle',
      58: 'Nièvre',
      59: 'Nord',
      60: 'Oise',
      61: 'Orne',
      62: 'Pas-de-Calais',
      63: 'Puy-de-Dôme',
      64: 'Pyrénées-Atlantiques',
      65: 'Pyrénées (Hautes)',
      66: 'Pyrénées-Orientales',
      67: 'Bas-Rhin',
      68: 'Haut-Rhin',
      69: 'Rhône',
      70: 'Saône (Haute)',
      71: 'Saône-et-Loire',
      72: 'Sarthe',
      73: 'Savoie',
      74: 'Savoie (Haute)',
      75: 'Paris',
      76: 'Seine-Maritime',
      77: 'Seine-et-Marne',
      78: 'Yvelines',
      79: 'Sèvres (Deux)',
      80: 'Somme',
      81: 'Tarn',
      82: 'Tarn-et-Garonne',
      83: 'Var',
      84: 'Vaucluse',
      85: 'Vendée',
      86: 'Vienne',
      87: 'Vienne (Haute)',
      88: 'Vosges',
      89: 'Yonne',
      90: 'Territ.-de-Belfort',
      91: 'Essonne',
      92: 'Hauts-de-Seine',
      93: 'Seine-Saint-Denis',
      94: 'Val-de-Marne',
      95: "Val-d'Oise",
      97: 'D.O.M.-T.O.M.',
      99: 'Hors-France',
    },
    GB: {
      AM: 'Armagh',
      AR: 'Ards',
      AT: 'Antrim',
      BA: 'Ballymena',
      BB: 'Blackburn',
      BE: 'Bedfordshire',
      BF: 'Bracknell Forest',
      BH: 'Brighton & Hove',
      BK: 'Berkshire',
      BL: 'Belfast',
      BM: 'Bournemouth',
      BN: 'Banbridge',
      BO: 'Borders',
      BP: 'Blackpool',
      BR: 'Bristol',
      BS: 'Bath&NthEstSomerset',
      BU: 'Buckinghamshire',
      BY: 'Ballymoney',
      CA: 'Cambridgeshire',
      CE: 'Central',
      CG: 'Craigavon',
      CH: 'Cheshire',
      CI: 'Coleraine',
      CK: 'Cookstown',
      CL: 'Clwyd',
      CO: 'Cornwall',
      CR: 'Carrickfergus',
      CS: 'Castlereagh',
      CU: 'Cumbria',
      CV: 'Cleveland',
      DB: 'Derbyshire',
      DF: 'Dumfries a. Galloway',
      DG: 'Dungannon',
      DL: 'Darlington',
      DN: 'Down',
      DO: 'Dorset',
      DU: 'Durham',
      DV: 'Devon',
      DY: 'Dyfed',
      ER: 'East Riding',
      ED: 'Edinburgh',
      ES: 'Essex',
      FI: 'Fife',
      FM: 'Fermanagh',
      GL: 'Gloucestershire',
      GM: 'Greater Manchester',
      GR: 'Grampian',
      GS: 'Sth. Gloucestershire',
      GW: 'Gwent',
      GY: 'Gwynedd',
      HA: 'Hampshire',
      HI: 'Highland',
      HL: 'Halton',
      HR: 'Hartlepool',
      HT: 'Hertfordshire',
      HW: 'Hereford and Worcs.',
      IW: 'Isle of Wight',
      KE: 'Kent',
      KH: 'Kingston-upon-Hull',
      LA: 'Lancashire',
      LC: 'Leicester City',
      LD: 'Londonderry',
      LE: 'Leicestershire',
      LI: 'Lincolnshire',
      LM: 'Limavady',
      LO: 'Greater London',
      LR: 'Larne',
      LS: 'Lisburn',
      LT: 'Lothian',
      LU: 'Luton',
      MA: 'Magherafelt',
      MG: 'Mid Glamorgan',
      MI: 'Middlesbrough',
      MK: 'Milton Keynes',
      MO: 'Moyle',
      MY: 'Merseyside',
      NA: 'Newtownabbey',
      NB: 'Newbury',
      NC: 'Nottingham City',
      ND: 'North Down',
      NE: 'NthEast Lincolnshire',
      NH: 'Northamptonshire',
      NK: 'Norfolk',
      NL: 'North Lincolnshire',
      NM: 'Newry and Mourne',
      NS: 'North Somerset',
      NT: 'Nottinghamshire',
      NU: 'Northumberland',
      OM: 'Omagh',
      OR: 'Orkney',
      OX: 'Oxfordshire',
      PB: 'Peterborough',
      PL: 'Poole',
      PM: 'Portsmouth',
      PO: 'Powys',
      PY: 'Plymouth',
      RD: 'Redcar and Cleveland',
      RE: 'Reading',
      RM: 'Rochester up. Medway',
      RU: 'Rutland',
      SC: 'Strathclyde',
      SD: 'Southend',
      SE: 'East Sussex',
      SG: 'South Glamorgan',
      SH: 'Shropshire',
      SK: 'Suffolk',
      SL: 'Shetland',
      SN: 'Stockton-on-Tees',
      SO: 'Somerset',
      SP: 'Southampton',
      SR: 'Strabane',
      ST: 'Staffordshire',
      SU: 'Slough',
      SW: 'West Sussex',
      SY: 'Surrey',
      TA: 'Tayside',
      TD: 'Thamesdown',
      TH: 'Thurrock',
      TO: 'Torbay',
      TW: 'Tyne and Wear',
      WA: 'Warwickshire',
      WD: 'Windsor & Maidenhead',
      WG: 'West Glamorgan',
      WI: 'Wiltshire',
      WL: 'Western Isles',
      WM: 'West Midlands',
      WO: 'Wokingham',
      WR: 'Wrekin',
      WT: 'Warrington',
      YK: 'York',
      YN: 'North Yorkshire',
      YS: 'South Yorkshire',
      YW: 'West Yorkshire',
    },
    GR: {
      1: 'Aitolia kai Akarnan.',
      2: 'Akhaia',
      3: 'Argolis',
      4: 'Arkadhia',
      5: 'Arta',
      6: 'Attiki',
      7: 'Dhodhekanisos',
      8: 'Dhrama',
      9: 'Evritania',
      10: 'Evros',
      11: 'Evvoia',
      12: 'Florina',
      13: 'Fokis',
      14: 'Fthiotis',
      15: 'Grevena',
      16: 'Ilia',
      17: 'Imathia',
      18: 'Ioannina',
      19: 'Iraklion',
      20: 'Kardhitsa',
      21: 'Kastoria',
      22: 'Kavala',
      23: 'Kefallinia',
      24: 'Kerkira',
      25: 'Khalkidhiki',
      26: 'Khania',
      27: 'Khios',
      28: 'Kikladhes',
      29: 'Kilkis',
      30: 'Korinthia',
      31: 'Kozani',
      32: 'Lakonia',
      33: 'Larisa',
      34: 'Lasithi',
      35: 'Lesvos',
      36: 'Levkas',
      37: 'Magnisia',
      38: 'Messinia',
      39: 'Pella',
      40: 'Pieria',
      41: 'Piraievs',
      42: 'Preveza',
      43: 'Rethimni',
      44: 'Rodhopi',
      45: 'Samos',
      46: 'Serrai',
      47: 'Thesprotia',
      48: 'Thessaloniki',
      49: 'Trikala',
      50: 'Voiotia',
      51: 'Xanthi',
      52: 'Zakinthos',
    },
    HK: {
      HK: 'Hong Kong Island',
      KLN: 'Kowloon',
      NT: 'New Territories',
    },
    HR: {
      1: 'Bjelovar-Bilogora',
      2: 'Stadt Zagreb',
      3: 'Dubrovnik-Neretva',
      4: 'Istra',
      5: 'Karlovac',
      6: 'Koprivnica-Krizevci',
      7: 'Lika-Senj',
      8: 'Medimurje',
      9: 'Osijek-Baranja',
      10: 'Pozega-Slavonija',
      11: 'Primorje-Gorski Kot.',
      12: 'Sibenik',
      13: 'Sisak-Moslavina',
      14: 'Slavonski',
      15: 'Brod-Posavina',
      16: 'Split-Dalmatia',
      17: 'Varazdin',
      18: 'Virovitica-Podravina',
      19: 'Vukovar-Srijem',
      20: 'Zadar-Knin',
      21: 'Zagreb',
    },
    HU: {
      1: 'Bacs-Kiskun',
      2: 'Baranya',
      3: 'Bekes',
      4: 'Bekescsaba',
      5: 'Borsod-Abauj-Zemplen',
      6: 'Budapest',
      7: 'Csongrad',
      8: 'Debrecen',
      9: 'Dunaujvaros',
      10: 'Eger',
      11: 'Fejer',
      12: 'Gyor',
      13: 'Gyor-Moson-Sopron',
      14: 'Hajdu-Bihar',
      15: 'Heves',
      16: 'Hodmezovasarhely',
      17: 'Jasz-Nagykun-Szolnok',
      18: 'Kaposvar',
      19: 'Kecskemet',
      20: 'Komarom-Esztergom',
      21: 'Miskolc',
      22: 'Nagykanizsa',
      23: 'Nograd',
      24: 'Nyiregyhaza',
      25: 'Pecs',
      26: 'Pest',
      27: 'Somogy',
      28: 'Sopron',
      29: 'Szabolcs-Szat.-Bereg',
      30: 'Szeged',
      31: 'Szekesfehervar',
      32: 'Szolnok',
      33: 'Szombathely',
      34: 'Tatabanya',
      35: 'Tolna',
      36: 'Vas',
      37: 'Veszprem',
      38: 'Zala',
      39: 'Zalaegerszeg',
    },
    ID: {
      1: 'DKI Jakarta Jakarta',
      2: 'Jawa Barat West Java',
      3: 'Jawa Tengah Central',
      4: 'Jawa Timur East Java',
      5: 'DI Yogyakarta Yogyak',
      6: 'DI Aceh Aceh',
      7: 'Sumatera Utara North',
      8: 'Sumatera Barat West',
      9: 'Riau Riau',
      10: 'Jambi Jambi',
      11: 'Sumatera Selatan Sou',
      12: 'Bengkulu Bengkulu',
      13: 'Lampung Lampung',
      14: 'Kalimantan Selatan S',
      15: 'Kalimantan Barat Wes',
      16: 'Kalimantan Tengah Ce',
      17: 'Kalimantan Timur Eas',
      18: 'Sulawesi Selatan Sou',
      19: 'Sulawesi Tenggara So',
      20: 'Sulawesi Tengah Cent',
      21: 'Sulawesi Utara North',
      22: 'Bali Bali',
      23: 'Nusa Tenggara Barat',
      24: 'Nusa Tenggara Timur',
      25: 'Maluku Maluku',
      26: 'Irian Jaya Irian Jay',
      27: 'Timor Timur East Tim',
    },
    IE: {
      CK: 'Cork',
      CL: 'Clare',
      CV: 'Cavan',
      CW: 'Carlow',
      DB: 'Dublin',
      DG: 'Donegal',
      GW: 'Galway',
      KD: 'Kildare',
      KK: 'Kilkenny',
      KY: 'Kerry',
      LF: 'Longford',
      LI: 'Limerick',
      LM: 'Leitrim',
      LS: 'Laois',
      LT: 'Louth',
      MH: 'Monaghan',
      MT: 'Meath',
      MY: 'Mayo',
      OF: 'Offaly',
      RC: 'Rosscommon',
      SG: 'Sligo',
      TP: 'Tipperary',
      WF: 'Waterford',
      WK: 'Wicklow',
      WM: 'Westmeath',
      WX: 'Wexford',
    },
    IL: {
      1: 'Central',
      2: 'Haifa',
      3: 'Jerusalem',
      4: 'Northern',
      5: 'Southern',
      6: 'Tel Aviv',
    },
    IN: {
      1: 'Andhra Pradesh',
      2: 'Arunachal Pradesh',
      3: 'Assam',
      4: 'Bihar',
      5: 'Goa',
      6: 'Gujarat',
      7: 'Haryana',
      8: 'Himachal Pradesh',
      9: 'Jammu and Kashmir',
      10: 'Karnataka',
      11: 'Kerala',
      12: 'Madhya Pradesh',
      13: 'Maharashtra',
      14: 'Manipur',
      15: 'Megalaya',
      16: 'Mizoram',
      17: 'Nagaland',
      18: 'Orissa',
      19: 'Punjab',
      20: 'Rajasthan',
      21: 'Sikkim',
      22: 'Tamil Nadu',
      TG: 'Telangana',
      23: 'Tripura',
      24: 'Uttar Pradesh',
      25: 'West Bengal',
      26: 'Andaman and Nico.In.',
      27: 'Chandigarh',
      28: 'Dadra and Nagar Hav.',
      29: 'Daman and Diu',
      30: 'Delhi',
      31: 'Lakshadweep',
      32: 'Pondicherry',
      33: 'Chhattisgarh',
      34: 'Jharkhand',
      35: 'Uttaranchal',
    },
    IT: {
      AG: 'Agriento',
      AL: 'Alessandria',
      AN: 'Ancona',
      AO: 'Aosta',
      AP: 'Ascoli Piceno',
      AQ: "L'Aquila",
      AR: 'Arezzo',
      AT: 'Asti',
      AV: 'Avellino',
      BA: 'Bari',
      BG: 'Bergamo',
      BI: 'Biella',
      BL: 'Belluno',
      BN: 'Benevento',
      BO: 'Bologna',
      BR: 'Brindisi',
      BS: 'Brescia',
      BZ: 'Bolzano',
      CA: 'Cagliari',
      CB: 'Campobasso',
      CE: 'Caserta',
      CH: 'Chieti',
      CL: 'Caltanisetta',
      CN: 'Cuneo',
      CO: 'Como',
      CR: 'Cremona',
      CS: 'Cosenza',
      CT: 'Catania',
      CZ: 'Catanzaro',
      EN: 'Enna',
      FE: 'Ferrara',
      FG: 'Foggia',
      FI: 'Florence',
      FO: 'Forlì',
      FR: 'Frosinone',
      GE: 'Genova',
      GO: 'Gorizia',
      GR: 'Grosseto',
      IM: 'Imperia',
      IS: 'Isernia',
      KR: 'Crotone',
      LC: 'Lecco',
      LE: 'Lecce',
      LI: 'Livorno',
      LO: 'Lodi',
      LT: 'Latina',
      LU: 'Lucca',
      MC: 'Macerata',
      ME: 'Messina',
      MI: 'Milan',
      MN: 'Mantova',
      MO: 'Modena',
      MS: 'Massa Carrara',
      MT: 'Matera',
      NA: 'Naples',
      NO: 'Novara',
      NU: 'Nuoro',
      OR: 'Oristano',
      PA: 'Palermo',
      PC: 'Piacenza',
      PD: 'Padova',
      PE: 'Pescara',
      PG: 'Perugia',
      PI: 'Pisa',
      PN: 'Pordenone',
      PO: 'Prato',
      PR: 'Parma',
      PS: 'Pesaro',
      PT: 'Pistoia',
      PU: 'Pesaro-Urbino',
      PV: 'Pavia',
      PZ: 'Potenza',
      RA: 'Ravenna',
      RC: 'Reggio Calabria',
      RE: 'Reggio Emilia',
      RG: 'Ragusa',
      RI: 'Rieti',
      RM: 'Rome',
      RN: 'Rimini',
      RO: 'Rovigo',
      RV: 'Rovigo',
      SA: 'Salerno',
      SI: 'Siena',
      SO: 'Sondrio',
      SP: 'La Spezia',
      SR: 'Siracusa',
      SS: 'Sassari',
      SV: 'Savona',
      TA: 'Taranto',
      TE: 'Teramo',
      TN: 'Trento',
      TO: 'Turin',
      TP: 'Trapani',
      TR: 'Terni',
      TS: 'Trieste',
      TV: 'Treviso',
      UD: 'Udine',
      VA: 'Varese',
      VC: 'Vercelli',
      VE: 'Venice',
      VI: 'Vicenza',
      VR: 'Verona',
      VT: 'Viterbo',
      VV: 'Vibo Valentia',
    },
    JP: {
      1: 'Hokkaido',
      2: 'Aomori-ken',
      3: 'Iwate-ken',
      4: 'Miyagi-ken',
      5: 'Akita-ken',
      6: 'Yamagata-ken',
      7: 'Fukushima-ken',
      8: 'Ibaraki-ken',
      9: 'Tochigi-ken',
      10: 'Gunma-ken',
      11: 'Saitama-ken',
      12: 'Chiba-ken',
      13: 'Tokyo-to',
      14: 'Kanagawa-ken',
      15: 'Niigata-ken',
      16: 'Toyama-ken',
      17: 'Ishikawa-ken',
      18: 'Fukui-ken',
      19: 'Yamanashi-ken',
      20: 'Nagano-ken',
      21: 'Gifu-ken',
      22: 'Shizuoka-ken',
      23: 'Aichi-ken',
      24: 'Mie-ken',
      25: 'Shiga-ken',
      26: 'Kyoto-fu',
      27: 'Osaka-fu',
      28: 'Hyogo-ken',
      29: 'Nara-ken',
      30: 'Wakayama-ken',
      31: 'Tottori-ken',
      32: 'Shimana-ken',
      33: 'Okayama-ken',
      34: 'Hiroshima-ken',
      35: 'Yamaguchi-ken',
      36: 'Tokushima-ken',
      37: 'Kagawa-ken',
      38: 'Ehima-ken',
      39: 'Kochi-ken',
      40: 'Fukuoka-ken',
      41: 'Saga-ken',
      42: 'Nagasaki-ken',
      43: 'Kumamoto-ken',
      44: 'Oita-ken',
      45: 'Miyazaki-ken',
      46: 'Kagoshima-ken',
      47: 'Okinawa-ken',
    },
    KR: {
      1: 'Cheju-do',
      2: 'Cholla-bukto',
      3: 'Cholla-namdo',
      4: 'Ch´ungch´ong-bukto',
      5: 'Ch´ungch´ong-namdo',
      6: 'Inch´on-jikhalsi',
      7: 'Kangwon-do',
      8: 'Kwangju-jikhalsi',
      9: 'Kyonggi-do',
      10: 'Kyongsang-bukto',
      11: 'Kyongsang-namdo',
      12: 'Pusan-jikhalsi',
      13: 'Soul-t´ukpyolsi',
      14: 'Taegu-jikhalsi',
      15: 'Taejon-jikhalsi',
    },
    KZ: {
      0: 'Almatynskaia',
      1: 'Kostanaiskaia',
      2: 'Severo-Kazakhstansk',
      3: 'Pavlodarskaia',
      4: 'Akmolinskaia',
      5: 'Aktubinskaia',
      6: 'Atyrauskaia',
      7: 'Zapadno-Kazakhst',
      8: 'Mangystayskaia',
      9: 'Karagandinskaia',
      10: 'Vostochno-Kazakhstan',
      11: 'Gambilskaia',
      12: 'Kyzilordinskaia',
    },
    MX: {
      AGS: 'Aguascalientes',
      BC: 'Baja California',
      BCS: 'Baja California S',
      CHI: 'Chihuahua',
      CHS: 'Chiapas',
      CMP: 'Campeche',
      COA: 'Coahuila',
      COL: 'Colima',
      DF: 'Distrito Federal',
      DGO: 'Durango',
      GRO: 'Guerrero',
      GTO: 'Guanajuato',
      HGO: 'Hidalgo',
      JAL: 'Jalisco',
      MCH: 'Michoacán',
      MEX: 'Estado de México',
      MOR: 'Morelos',
      NAY: 'Nayarit',
      NL: 'Nuevo Léon',
      OAX: 'Oaxaca',
      PUE: 'Puebla',
      QR: 'Quintana Roo',
      QRO: 'Querétaro',
      SIN: 'Sinaloa',
      SLP: 'San Luis Potosí',
      SON: 'Sonora',
      TAB: 'Tabasco',
      TLX: 'Tlaxcala',
      TMS: 'Tamaulipas',
      VER: 'Veracruz',
      YUC: 'Yucatán',
      ZAC: 'Zacatecas',
    },
    MY: {
      JOH: 'Johor',
      KED: 'Kedah',
      KEL: 'Kelantan',
      KUL: 'Kuala Lumpur',
      LAB: 'Labuan',
      MEL: 'Melaka',
      PAH: 'Pahang',
      PEL: 'Perlis',
      PER: 'Perak',
      PIN: 'Pulau Pinang',
      SAB: 'Sabah',
      SAR: 'Sarawak',
      SEL: 'Selangor',
      SER: 'Negeri Sembilan',
      TRE: 'Trengganu',
    },
    NL: {
      1: 'Drenthe',
      2: 'Flevoland',
      3: 'Friesland',
      4: 'Gelderland',
      5: 'Groningen',
      6: 'Limburg',
      7: 'Noord-Brabant',
      8: 'Noord-Holland',
      9: 'Overijssel',
      10: 'Utrecht',
      11: 'Zeeland',
      12: 'Zuid-Holland',
    },
    NO: {
      1: 'Østfold Fylke',
      2: 'Akershus Fylke',
      3: 'Oslo',
      4: 'Hedmark Fylke',
      5: 'Oppland Fylke',
      6: 'Buskerud Fylke',
      7: 'Vestfold Fylke',
      8: 'Telemark Fylke',
      9: 'Aust-Agder Fylke',
      10: 'Vest-Agder Fylke',
      11: 'Rogaland Fylke',
      12: 'Hordaland Fylke',
      14: 'Sogn og Fjordane F.',
      15: 'Møre og Romsdal F.',
      16: 'Sør-Trøndelag Fylke',
      17: 'Nord-Trøndelag Fylke',
      18: 'Nordland Fylke',
      19: 'Troms Fylke',
      20: 'Finnmark Fylke',
    },
    NZ: {
      AKL: 'Auckland',
      BOP: 'Bay of Plenty',
      CAN: 'Canterbury',
      HAB: 'Hawke´s Bay',
      MAN: 'Manawatu-Wanganui',
      NTL: 'Northland',
      OTA: 'Otago',
      STL: 'Southland',
      TAR: 'Taranaki',
      WAI: 'Waikato',
      WEC: 'West Coast',
      WLG: 'Wellington',
    },
    PE: {
      1: 'Tumbes',
      2: 'Piura',
      3: 'Lambayeque',
      4: 'La Libertad',
      5: 'Ancash',
      6: 'Lima y Callao',
      7: 'Ica',
      8: 'Arequipa',
      9: 'Moquegua',
      10: 'Tacna',
      11: 'Amazon',
      12: 'Cajamarca',
      13: 'San Martín',
      14: 'Huánuco',
      15: 'Pasco',
      16: 'Junín',
      17: 'Huancavelica',
      18: 'Ayacucho',
      19: 'Apurimac',
      20: 'Cuzco',
      21: 'Puno',
      22: 'Loreto',
      23: 'Ucayali',
      24: 'Madre de Díos',
    },
    PH: {
      1: 'Ilocos',
      2: 'Cagayan Valley',
      3: 'Central Luzon',
      4: 'South Luzon',
      5: 'Bicol',
      6: 'West Visayas',
      7: 'Central Visayas',
      8: 'Eastern Visayas',
      9: 'Western Mindanao',
      10: 'Northern Mindanao',
      11: 'Central Mindanao',
      12: 'South Mindanao',
      13: 'Manila',
    },
    PL: {
      1: 'Biala Podlaska',
      2: 'Bialystok',
      3: 'Bielsko Biala',
      4: 'Bydgoszcz',
      5: 'Chelm',
      6: 'Ciechanow',
      7: 'Czestochowa',
      8: 'Elblag',
      9: 'Gdansk',
      10: 'Gorzow',
      11: 'Jelenia Gora',
      12: 'Kalisz',
      13: 'Katowice',
      14: 'Kielce',
      15: 'Konin',
      16: 'Koszalin',
      17: 'Krakow',
      18: 'Krosno',
      19: 'Legnica',
      20: 'Leszno',
      21: 'Lodz',
      22: 'Lomza',
      23: 'Lublin',
      24: 'Nowy Sacz',
      25: 'Olsztyn',
      26: 'Opole',
      27: 'Ostroleka',
      28: 'Pila',
      29: 'Piotrkow',
      30: 'Plock',
      31: 'Poznan',
      32: 'Przemysl',
      33: 'Radom',
      34: 'Rzeszow',
      35: 'Siedlce',
      36: 'Sieradz',
      37: 'Skierniewice',
      38: 'Slupsk',
      39: 'Suwalki',
      40: 'Szczecin',
      41: 'Tarnobrzeg',
      42: 'Tarnow',
      43: 'Torun',
      44: 'Walbrzych',
      45: 'Warszawa',
      46: 'Wloclawek',
      47: 'Wroclaw',
      48: 'Zamosc',
      49: 'Zielona Gora',
    },
    PT: {
      10: 'Minho-Lima',
      11: 'Cávado',
      12: 'Ave',
      13: 'Grande Porto',
      14: 'Tâmega',
      15: 'Entre Douro e Vouga',
      16: 'Douro',
      17: 'Alto Trás-os-Montes',
      20: 'Baixo Vouga',
      21: 'Baixo Mondego',
      22: 'Pinhal Litoral',
      23: 'Pinhal Interior N.',
      24: 'Pinhal Interior Sul',
      25: 'Dão-Lafoes',
      26: 'Serra da Estrela',
      27: 'Beira Interior Norte',
      28: 'Beira Interior Sul',
      29: 'Cova da Beira',
      30: 'Oeste',
      31: 'Grande Lisboa',
      32: 'Península de Setúbal',
      33: 'Médio Tejo',
      34: 'Lezíria do Tejo',
      40: 'Alentejo Litoral',
      41: 'Alto Alentejo',
      42: 'Alentejo Central',
      43: 'Baixo Alentejo',
      50: 'Algarve',
      60: 'Reg. Aut. dos Açores',
      70: 'Reg. Aut. da Madeira',
    },
    RO: {
      1: 'Alba',
      2: 'Arad',
      3: 'Arges',
      4: 'Bacau',
      5: 'Bihor',
      6: 'Bistrita-Nasaud',
      7: 'Botosani',
      8: 'Braila',
      9: 'Brasov',
      10: 'Bucuresti',
      11: 'Buzau',
      12: 'Calarasi',
      13: 'Caras-Severin',
      14: 'Cluj',
      15: 'Constanta',
      16: 'Covasna',
      17: 'Dimbovita',
      18: 'Dolj',
      19: 'Galati',
      20: 'Gorj',
      21: 'Giurgiu',
      22: 'Harghita',
      23: 'Hunedoara',
      24: 'Ialomita',
      25: 'Iasi',
      26: 'Maramures',
      27: 'Mehedinti',
      28: 'Mures',
      29: 'Neamt',
      30: 'Olt',
      31: 'Prahova',
      32: 'Salaj',
      33: 'Satu Mare',
      34: 'Sibiu',
      35: 'Suceava',
      36: 'Teleorman',
      37: 'Timis',
      38: 'Tulcea',
      39: 'Vaslui',
      40: 'Vilcea',
      41: 'Vrancea',
    },
    RS: {
      1: 'Bor District',
      2: 'Branicevo District',
      3: 'Jablanica District',
      4: 'Kolubara District',
      5: 'Macva District',
      6: 'Moravica District',
      7: 'Nisava District',
      8: 'Pcinja District',
      9: 'Pirot District',
      10: 'Podunavlje District',
      11: 'Pomoravlje District',
      12: 'Rasina District',
      13: 'Raska District',
      14: 'Sumadija District',
      15: 'Toplica District',
      16: 'Zajecar District',
      17: 'Zlatibor District',
      18: 'Central Banat Distri',
      19: 'North Backa District',
      20: 'North Banat District',
      21: 'South Backa District',
      22: 'South Banat District',
      23: 'Srem District',
      24: 'West Backa District',
      25: 'Djakovica District',
      26: 'Gnjilane District',
      27: 'Kosovska Mitrovica D',
      28: 'Pec District',
      29: 'Pristina District',
      30: 'Prizren District',
      31: 'Urosevac District',
    },
    RU: {
      1: 'Adigeja Republic',
      2: 'Highlands-Altay Rep.',
      3: 'Republ.of Bashkortos',
      4: 'Buryat Republic',
      5: 'Dagestan Republic',
      6: 'Ingushetija Republic',
      7: 'Kabardino-Balkar.Rep',
      8: 'Kalmyk Republic',
      9: 'Karach.-Cherkessk Re',
      10: 'Karelian Republic',
      11: 'Komi Republic',
      12: 'Marijskaya Republic',
      13: 'Mordovian Republic',
      14: 'Yakutiya-Saha Rrepub',
      15: 'North-Osetiya Republ',
      16: 'Tatarstan Republic',
      17: 'Tuva Republic',
      18: 'The Udmurt Republic',
      19: 'Chakassky Republic',
      20: 'Chechenskaya Republ.',
      21: 'Chuvash Republic',
      22: 'Altay Territory',
      23: 'Krasnodar Territory',
      24: 'Krasnoyarsk Territor',
      25: 'Primorye Territory',
      26: 'Stavropol Territory',
      27: 'Khabarovsk Territory',
      28: 'The Amur Area',
      29: 'The Arkhangelsk Area',
      30: 'The Astrakhan Area',
      31: 'The Belgorod Area',
      32: 'The Bryansk Area',
      33: 'The Vladimir Area',
      34: 'The Volgograd Area',
      35: 'The Vologda Area',
      36: 'The Voronezh Area',
      37: 'The Ivanovo Area',
      38: 'The Irkutsk Area',
      39: 'The Kaliningrad Area',
      40: 'The Kaluga Area',
      41: 'The Kamchatka Area',
      42: 'The Kemerovo Area',
      43: 'The Kirov Area',
      44: 'The Kostroma Area',
      45: 'The Kurgan Area',
      46: 'The Kursk Area',
      47: 'The Leningrad Area',
      48: 'The Lipetsk Area',
      49: 'The Magadan Area',
      50: 'The Moscow Area',
      51: 'The Murmansk Area',
      52: 'The Nizhniy Novgorod',
      53: 'The Novgorod Area',
      54: 'The Novosibirsk Area',
      55: 'The Omsk Area',
      56: 'The Orenburg Area',
      57: 'The Oryol Area',
      58: 'The Penza Area',
      59: 'The Perm Area',
      60: 'The Pskov Area',
      61: 'The Rostov Area',
      62: 'The Ryazan Area',
      63: 'The Samara Area',
      64: 'The Saratov Area',
      65: 'The Sakhalin Area',
      66: 'The Sverdlovsk Area',
      67: 'The Smolensk Area',
      68: 'The Tambov Area',
      69: 'The Tver Area',
      70: 'The Tomsk Area',
      71: 'The Tula Area',
      72: 'The Tyumen Area',
      73: 'The Ulyanovsk Area',
      74: 'The Chelyabinsk Area',
      75: 'The Chita Area',
      76: 'The Yaroslavl Area',
      77: 'c.Moscow',
      78: 'c.St-Peterburg',
      79: 'The Jewish Auton.are',
      80: 'Aginsk Buryat Aut.di',
      81: 'Komy Permjats.Aut.di',
      82: 'Korjacs Auton.distri',
      83: 'Nenekchky Auton.dist',
      84: 'The Taymir Auton.dis',
      85: 'Ust-Ordinsky Buryat',
      86: 'Chanti-Mansyjsky Aut',
      87: 'Chukotka Auton. dist',
      88: 'Evensky Auton.distri',
      89: 'Jamalo-Nenekchky Aut',
    },
    SE: {
      1: 'Blekinge Län',
      2: 'Dalarnas Län',
      3: 'Gotlands Län',
      4: 'Gävleborgs Län',
      5: 'Hallands Län',
      6: 'Jämtlands Län',
      7: 'Jönköpings Län',
      8: 'Kalmar Län',
      9: 'Kronobergs Län',
      10: 'Norrbottens Län',
      11: 'Skåne Län',
      12: 'Stockholms Län',
      13: 'Södermanlands Län',
      14: 'Uppsala Län',
      15: 'Värmlands Län',
      16: 'Västerbottens Län',
      17: 'Västernorrlands Län',
      18: 'Västmanlands Län',
      19: 'Västra Götalands Län',
      20: 'Örebro Län',
      21: 'Östergötlands Län',
    },
    SG: {
      SG: 'Singapore',
    },
    SI: {
      1: 'Ajdovscina',
      2: 'Brezice',
      3: 'Celje',
      4: 'Cerknica',
      5: 'Crnomelj',
      6: 'Dravograd',
      7: 'Gornja Radgona',
      8: 'Grosuplje',
      9: 'Hrastnik Lasko',
      10: 'Idrija',
      11: 'Ilirska Bistrica',
      12: 'Izola',
      13: 'Jesenice',
      14: 'Kamnik',
      15: 'Kocevje',
      16: 'Koper',
      17: 'Kranj',
      18: 'Krsko',
      19: 'Lenart',
      20: 'Lendava',
      21: 'Litija',
      22: 'Ljubljana-Bezigrad',
      23: 'Ljubljana-Center',
      24: 'Ljubljana-Moste-Polj',
      25: 'Ljubljana-Siska',
      26: 'Ljubljana-Vic-Rudnik',
      27: 'Ljutomer',
      28: 'Logatec',
      29: 'Maribor',
      30: 'Metlika',
      31: 'Mozirje',
      32: 'Murska Sobota',
      33: 'Nova Gorica',
      34: 'Novo Mesto',
      35: 'Ormoz',
      36: 'Pesnica',
      37: 'Piran',
      38: 'Postojna',
      39: 'Ptuj',
      40: 'Radlje Ob Dravi',
      41: 'Radovljica',
      42: 'Ravne Na Koroskem',
      43: 'Ribnica',
      44: 'Ruse',
      45: 'Sentjur Pri Celju',
      46: 'Sevnica',
      47: 'Sezana',
      48: 'Skofja Loka',
      49: 'Slovenj Gradec',
      50: 'Slovenska Bistrica',
      51: 'Slovenske Konjice',
      52: 'Smarje Pri Jelsah',
      53: 'Tolmin',
      54: 'Trbovlje',
      55: 'Trebnje',
      56: 'Trzic',
      57: 'Velenje',
      58: 'Vrhnika',
      59: 'Zagorje Ob Savi',
      60: 'Zalec',
    },
    SK: {
      1: 'Bratislava',
      2: 'Zapadoslovensky',
      3: 'Stredoslovensky',
      4: 'Vychodoslovensky',
    },
    SZ: {
      H: 'Hhohho',
      L: 'Lubombo',
      M: 'Manzini',
      S: 'Shishelweni',
    },
    TH: {
      1: 'Amnat Charoen',
      2: 'Ang Thong',
      3: 'Bangkok',
      4: 'Buriram',
      5: 'Chachoengsao',
      6: 'Chai Nat',
      7: 'Chaiyaphum',
      8: 'Chanthaburi',
      9: 'Chiang Mai',
      10: 'Chiang Rai',
      11: 'Chon Buri',
      12: 'Chumphon',
      13: 'Kalasin',
      14: 'Kamphaeng Phet',
      15: 'Kanchanaburi',
      16: 'Khon Kaen',
      17: 'Krabi',
      18: 'Krung Thep',
      19: 'Mahanakhon',
      20: 'Lampang',
      21: 'Lamphun',
      22: 'Loei',
      23: 'Lop Buri',
      24: 'Mae Hong Son',
      25: 'Maha Sarakham',
      26: 'Mukdahan',
      27: 'Nakhon Nayok',
      28: 'Nakhon Pathom',
      29: 'Nakhon Phanom',
      30: 'Nakhon Ratchasima',
      31: 'Nakhon Sawan',
      32: 'Nakhon Si Thammarat',
      33: 'Nan',
      34: 'Narathiwat',
      35: 'Nong Bua Lamphu',
      36: 'Nong Khai',
      37: 'Nonthaburi',
      38: 'Pathum Thani',
      39: 'Pattani',
      40: 'Phangnga',
      41: 'Phatthalung',
      42: 'Phayao',
      43: 'Phetchabun',
      44: 'Phetchaburi',
      45: 'Phichit',
      46: 'Phitsanulok',
      47: 'Phra Nakhon Si Ayut.',
      48: 'Phrae',
      49: 'Phuket',
      50: 'Prachin Buri',
      51: 'Rayong',
    },
    TR: {
      1: 'Adana',
      2: 'Adiyaman',
      3: 'Afyon',
      4: 'Agri',
      5: 'Amasya',
      6: 'Ankara',
      7: 'Antalya',
      8: 'Artvin',
      9: 'Aydin',
      10: 'Balikesir',
      11: 'Bilecik',
      12: 'Bingöl',
      13: 'Bitlis',
      14: 'Bolu',
      15: 'Burdur',
      16: 'Bursa',
      17: 'Canakkale',
      18: 'Cankiri',
      19: 'Corum',
      20: 'Denizli',
      21: 'Diyarbakir',
      22: 'Edirne',
      23: 'Elazig',
      24: 'Erzincan',
      25: 'Erzurum',
      26: 'Eskisehir',
      27: 'Gaziantep',
      28: 'Giresun',
      29: 'Gümüshane',
      30: 'Hakkari',
      31: 'Hatay',
      32: 'Isparta',
      33: 'Icel',
      34: 'Istanbul',
      35: 'Izmir',
      36: 'Kars',
      37: 'Kastamonu',
      38: 'Kayseri',
      39: 'Kirklareli',
      40: 'Kirshehir',
      41: 'Kocaeli',
      42: 'Konya',
      43: 'Kütahya',
      44: 'Malatya',
      45: 'Manisa',
      46: 'K.Marash',
      47: 'Mardin',
      48: 'Mugla',
      49: 'Mush',
      50: 'Nevshehir',
      51: 'Nigde',
      52: 'Ordu',
      53: 'Rize',
      54: 'Sakarya',
      55: 'Samsun',
      56: 'Siirt',
      57: 'Sinop',
      58: 'Sivas',
      59: 'Tekirdag',
      60: 'Tokat',
      61: 'Trabzon',
      62: 'Tunceli',
      63: 'Shanliurfa',
      64: 'Ushak',
      65: 'Van',
      66: 'Yozgat',
      67: 'Zonguldak',
      68: 'Aksaray',
      69: 'Bayburt',
      70: 'Karaman',
      71: 'Kirikkale',
      72: 'Batman',
      73: 'Shirnak',
      74: 'Bartin',
      75: 'Ardahan',
      76: 'Igdir',
      77: 'Yalova',
    },
    TW: {
      FJN: 'Fu-chien',
      KSH: 'Kao-hsiung',
      TPE: 'T´ai-pei',
      TWN: 'Taiwan',
    },
    UA: {
      CHG: "Chernigivs'ka",
      CHR: "Cherkas'ka",
      CHV: "Chernovits'ka",
      DNP: "Dnipropetrovs'ka",
      DON: "Donets'ka",
      HAR: "Harkivs'ka",
      HML: "Hmel'nits'ka",
      HRS: "Hersons'ka",
      IVF: "Ivano-Frankivs'ka",
      KIE: "Kievs'ka",
      KIR: "Kirovograds'ka",
      KRM: 'Respublika Krim',
      LV: "L'vivsbka",
      LUG: "Lugans'ka",
      MIK: "Mikolaivs'ka",
      M_K: 'm.Kiev',
      M_S: 'm.Sevastopil',
      ODS: "Odes'ka",
      POL: "Poltavs'ka",
      RIV: "Rivnens'ka",
      SUM: "Sums'ka",
      TER: "Ternopil's'ka",
      VIN: "Vinnits'ka",
      VOL: "Volins'ka",
      ZAK: "Zakarpats'ka",
      ZAP: "Zaporiz'ka",
      ZHI: "Zhitomirs'ka",
    },
    US: {
      AK: 'Alaska',
      AL: 'Alabama',
      AR: 'Arkansas',
      AS: 'American Samoa',
      AZ: 'Arizona',
      CA: 'California',
      CO: 'Colorado',
      CT: 'Connecticut',
      DC: 'District of Columbia',
      DE: 'Delaware',
      FL: 'Florida',
      GA: 'Georgia',
      GU: 'Guam',
      HI: 'Hawaii',
      IA: 'Iowa',
      ID: 'Idaho',
      IL: 'Illinois',
      IN: 'Indiana',
      KS: 'Kansas',
      KY: 'Kentucky',
      LA: 'Louisiana',
      MA: 'Massachusetts',
      MD: 'Maryland',
      ME: 'Maine',
      MI: 'Michigan',
      MN: 'Minnesota',
      MO: 'Missouri',
      MP: 'Northern Mariana Isl',
      MS: 'Mississippi',
      MT: 'Montana',
      NC: 'North Carolina',
      ND: 'North Dakota',
      NE: 'Nebraska',
      NH: 'New Hampshire',
      NJ: 'New Jersey',
      NM: 'New Mexico',
      NV: 'Nevada',
      NY: 'New York',
      OH: 'Ohio',
      OK: 'Oklahoma',
      OR: 'Oregon',
      PA: 'Pennsylvania',
      PR: 'Puerto Rico',
      RI: 'Rhode Island',
      SC: 'South Carolina',
      SD: 'South Dakota',
      TN: 'Tennessee',
      TX: 'Texas',
      UT: 'Utah',
      VA: 'Virginia',
      VI: 'Virgin Islands',
      VT: 'Vermont',
      WA: 'Washington',
      WI: 'Wisconsin',
      WV: 'West Virginia',
      WY: 'Wyoming',
    },
    VE: {
      AMA: 'Amazon',
      ANZ: 'Anzoategui',
      APU: 'Apure',
      ARA: 'Aragua',
      BAR: 'Barinas',
      BOL: 'Bolivar',
      CAR: 'Carabobo',
      COJ: 'Cojedes',
      DA: 'Delta Amacuro',
      DF: 'Distrito Federal',
      FAL: 'Falcon',
      GUA: 'Guarico',
      LAR: 'Lara',
      MER: 'Merida',
      MIR: 'Miranda',
      MON: 'Monagas',
      NE: 'Nueva Esparta',
      POR: 'Portuguesa',
      SUC: 'Sucre',
      TAC: 'Tachira',
      TRU: 'Trujillo',
      VAR: 'Vargas',
      YAR: 'Yaracuy',
      ZUL: 'Zulia',
    },
    ZA: {
      EC: 'Eastern Cape',
      FS: 'Freestate',
      GP: 'Gauteng',
      KZN: 'Kwazulu/Natal',
      MP: 'Mpumalanga',
      NC: 'Northern Cape',
      NP: 'Northern Province',
      NW: 'North-West',
      WC: 'Western Cape',
    },
  },
})
