export default () => ({
  spaceTypes: [],
  hsrSpaceTypes: [],
  industry: [
    { label: 'Agriculture', value: 'Agriculture' },
    { label: 'Apparel', value: 'Apparel' },
    { label: 'Architecture', value: 'Architecture' },
    { label: 'Banking', value: 'Banking' },
    { label: 'Biotechnology', value: 'Biotechnology' },
    { label: 'Chemicals', value: 'Chemicals' },
    { label: 'Communications', value: 'Communications' },
    { label: 'Construction', value: 'Construction' },
    { label: 'Consulting', value: 'Consulting' },
    { label: 'Education', value: 'Education' },
    { label: 'Electronics', value: 'Electronics' },
    { label: 'Energy', value: 'Energy' },
    { label: 'Engineering', value: 'Engineering' },
    { label: 'Entertainment', value: 'Entertainment' },
    { label: 'Environmental', value: 'Environmental' },
    { label: 'Finance', value: 'Finance' },
    { label: 'Food & Beverage', value: 'Food & Beverage' },
    { label: 'Government', value: 'Government' },
    { label: 'Healthcare', value: 'Healthcare' },
    { label: 'Hospitality', value: 'Hospitality' },
    { label: 'Insurance', value: 'Insurance' },
    { value: 'Legal', label: 'Legal' },
    { label: 'Machinery', value: 'Machinery' },
    { label: 'Manufacturing', value: 'Manufacturing' },
    { label: 'Media', value: 'Media' },
    { label: 'Not For Profit', value: 'Not For Profit' },
    { label: 'Real Estate', value: 'Real Estate' },
    { label: 'Recreation', value: 'Recreation' },
    { label: 'Retail', value: 'Retail' },
    { label: 'Technology', value: 'Technology' },
    { label: 'Telecommunications', value: 'Telecommunications' },
    { label: 'Transportation', value: 'Transportation' },
    { label: 'Utilities', value: 'Utilities' },
    { label: 'Other', value: 'Other' },
  ],
  activeTab: null,
  loading: false,
  mode: 'register',
  wprMode: 'register',
  currentStep: 0,
  adminPortfolioList: null,
  sharedWorkspace: {},
  currentPage: 1,
  allInvoices: [],
  pricingDetails: null,
  portfolio: null,
  portfolioInvoices: null,
  paginatedLocations: null,
  allLocations: null,
  subsetProjects: [],
  scorecardDocuments: [],
  scorecardAuditDocuments: [],
  projectSummary: [],
  documentsList: [{ data: [] }],
  documents: null,
  wprDocuments: null,
  featureandParts: [],
  showFeatures: false,
  strategies: null,
  coachingContacts: [],
  wellReviewers: [],
  externalReviewers: [],
  ptAgents: [],
  legalTypes: [
    {
      label: 'Signed certification agreement',
      value: 'Signed certification agreement',
    },
    { label: 'CA', value: 'CA' },
    { label: 'Conf agents auth', value: 'Conf agents auth' },
    { label: 'Change of primary owner', value: 'Change of primary owner' },
  ],
  generalTypes: [
    { label: 'Project overview', value: 'Project overview' },
    {
      label: 'Location floor plans or visuals',
      value: 'Location floor plans or visuals',
    },
    { label: 'Certificate of occupancy', value: 'Certificate of occupancy' },
  ],
  featureLocationOptions: [
    { label: 'Single location', value: 'single' },
    { label: 'Multiple locations or subsets', value: 'multiple' },
    { label: 'All locations', value: 'all' },
  ],
  verificationImpementOptions: [
    {
      label: 'Yes, the items being verified are in place already.',
      value: 'Implementation',
    },
    {
      label: 'No, the items being verified are intent-based only.',
      value: 'Intent',
    },
  ],
  sharedFilters: {},
  subsetList: [],
  filters: {
    filter_space_type: [],
    filter_project_type: [],
    filter_location: [],
    filter_industry: [],
    filter_area: '',
    filter_construction_status: [],
    filter_construction_type: [],
    deleted_at: 'all',
  },
  subsetFilters: {
    filter_space_type: [],
    filter_project_type: [],
    filter_location: [],
    filter_industry: [],
    filter_area: '',
    filter_construction_status: [],
    filter_construction_type: [],
  },
  projectType: [
    { value: 'new-existing', label: 'Owner-occupied' },
    { value: 'cs', label: 'For sale/lease' },
    { value: 'cics', label: 'Tenancy' },
  ],
  wellStandardList: [
    {
      label: 'WELL Building Standard for Commercial & Institutional Office',
      value: 'office',
    },
    {
      label: 'WELL Building Standard for Multifamily Residential (Pilot)',
      value: 'residential',
    },
    { label: 'WELL Building Standard for Retail (Pilot)', value: 'retail' },
    {
      label: 'WELL Building Standard for Educational Facilities (Pilot)',
      value: 'education',
    },
    {
      label: 'WELL Building Standard for Restaurants (Pilot)',
      value: 'restaurant',
    },
    { label: 'WELL Community', value: 'community' },
  ],
})
