export default () => ({
  scorecard: null,
  hsrScorecard: null,
  concepts: null,
  verifications: null,
  annotatedDocuments: null,
  letterOfAssurances: null,
  onSites: null,
  filteredParts: [],
  scorecardVersion: '',
  glossaryTerm: [],
  activeFilters: {
    concept: 'All',
    response: [],
    name: '',
    verification: '',
    on_site: '',
    loa: '',
    annotated_doc: '',
    point_weight: null,
    show_preconditions: true,
    show_optimizations: true,
    doc_count: null,
    note_count: null,
    imperial: false,
  },
  documents: null,
  conceptPrePrec: 0,
  conceptOptPrec: 0,
  scoresSummary: null,
  anticipatedScore: 0,
  conceptPoints: 0,
  conceptSummary: null,
  adminReviewResponses: [],
  partGuidance: null,
  guidancePopover: [
    {
      value: 'Whole Building',
      text: 'All areas within the project boundary. If the Core Applicability Matrix indicates that projects can achieve a feature by providing a tenant budget, then project teams need to submit as part of documentation review design assumptions and sample cut-sheets (as applicable) that justify the budget and can be used by the tenant during their design and construction process.',
    },
    {
      value: 'Extent of Developer Buildout',
      text: 'Includes all non-leased space and all construction within the leased space for which the project team is responsible.',
    },
    {
      value: 'Leased Spaces',
      text: 'All areas within the project boundary that are leased to or owned by tenants.',
    },
    {
      value: 'Non-leased Spaces',
      text: 'All areas within the project boundary that is not considered leased space.',
    },
    {
      value: 'Building management staff',
      text: 'Individuals responsible for maintaining and operating the building, including contractors and sub-contractors. Workers who spend less than 30 hours per month in the building (i.e., who are not regular building occupants) are not considered building management staff.',
    },
    {
      value: 'Direct staff',
      text: 'Building staff under direct employ. Note: If a project has no direct-staff on-site (i.e., the building is entirely operated by contracted building management staff), the project is allowed to earn points by meeting feature requirements for all or a defined subset of building management staff. Project must use a single consistent population across all features including preconditions (e.g., a project with no direct-staff may only earn a point for meeting an optimization for its building management staff if it also meets all preconditions for that same group of people).',
    },
    {
      value: 'WELL Core',
      text: 'Encompasses all projects registered for WELL Core, including commercial and multifamily residential projects.',
    },
    {
      value: 'MFR Core',
      text: 'Refers to multifamily residential projects using WELL Core.',
    },
    {
      value: 'Commercial Core',
      text: 'Refers to all non-multifamily residential projects using WELL Core.',
    },
    {
      value: 'MFR Certification',
      text: 'Refers to all multifamily residential projects not using WELL Core. ',
    },
  ],
  isActiveChecklist: true,
  documentsChange: true,
})
