export default () => ({
  feature: null,
  features: null,
  staticV1Features: {
    '01-air-quality-standards': '01 - Air quality standards',
    '02-smoking-ban': '02 - Smoking ban',
    '03-ventilation-effectiveness': '03 - Ventilation effectiveness',
    '04-voc-reduction': '04 - VOC reduction',
    '05-air-filtration': '05 - Air filtration',
    '06-microbe-and-mold-control': '06 - Microbe and mold control',
    '07-construction-pollution-management':
      '07 - Construction pollution management',
    '08-healthy-entrance': '08 - Healthy entrance',
    '09-cleaning-protocol': '09 - Cleaning protocol',
    '10-pesticide-management': '10 - Pesticide management',
    '11-fundamental-material-safety': '11 - Fundamental material safety',
    '12-moisture-management': '12 - Moisture management',
    '13-air-flush': '13 - Air flush',
    '14-air-infiltration-management': '14 - Air infiltration management',
    '15-increased-ventilation': '15 - Increased ventilation',
    '16-humidity-control': '16 - Humidity control',
    '17-direct-source-ventilation': '17 - Direct source ventilation',
    '18-air-quality-monitoring-and-feedback':
      '18 - Air quality monitoring and feedback',
    '19-operable-windows': '19 - Operable windows',
    '20-outdoor-air-systems': '20 - Outdoor air systems',
    '21-displacement-ventilation': '21 - Displacement ventilation',
    '22-pest-control': '22 - Pest control',
    '23-advanced-air-purification': '23 - Advanced air purification',
    '24-combustion-minimization': '24 - Combustion minimization',
    '25-toxic-material-reduction': '25 - Toxic material reduction',
    '26-enhanced-material-safety': '26 - Enhanced material safety',
    '27-antimicrobial-activity-for-surfaces':
      '27 - Antimicrobial activity for surfaces',
    '28-cleanable-environment': '28 - Cleanable environment',
    '29-cleaning-equipment': '29 - Cleaning equipment',
    '30-fundamental-water-quality': '30 - Fundamental water quality',
    '31-inorganic-contaminants': '31 - Inorganic contaminants',
    '32-organic-contaminants': '32 - Organic contaminants',
    '33-agricultural-contaminants': '33 - Agricultural contaminants',
    '34-public-water-additives': '34 - Public water additives',
    '35-periodic-water-quality-testing': '35 - Periodic water quality testing',
    '36-water-treatment': '36 - Water treatment',
    '37-drinking-water-promotion': '37 - Drinking water promotion',
    '38-fruits-and-vegetables': '38 - Fruits and vegetables',
    '39-processed-foods': '39 - Processed foods',
    '40-food-allergies': '40 - Food allergies',
    '41-hand-washing': '41 - Hand washing',
    '42-food-contamination': '42 - Food contamination',
    '43-artificial-ingredients': '43 - Artificial ingredients',
    '44-nutritional-information': '44 - Nutritional information',
    '45-food-advertising': '45 - Food advertising',
    '46-safe-food-preparation-materials':
      '46 - Safe food preparation materials',
    '47-serving-sizes': '47 - Serving sizes',
    '48-special-diets': '48 - Special diets',
    '49-responsible-food-production': '49 - Responsible food production',
    '50-food-storage': '50 - Food storage',
    '51-food-production': '51 - Food production',
    '52-mindful-eating': '52 - Mindful eating',
    '53-visual-lighting-design': '53 - Visual lighting design',
    '54-circadian-lighting-design': '54 - Circadian lighting design',
    '55-electric-light-glare-control': '55 - Electric light glare control',
    '56-solar-glare-control': '56 - Solar glare control',
    '57-lowglare-workstation-design': '57 - Low-glare workstation design',
    '58-color-quality': '58 - Color quality',
    '59-surface-design': '59 - Surface design',
    '60-automated-shading-and-dimming-controls':
      '60 - Automated shading and dimming controls',
    '61-right-to-light': '61 - Right to light',
    '62-daylight-modeling': '62 - Daylight modeling',
    '63-daylighting-fenestration': '63 - Daylighting fenestration',
    '64-interior-fitness-circulation': '64 - Interior fitness circulation',
    '65-activity-incentive-programs': '65 - Activity incentive programs',
    '66-structured-fitness-opportunities':
      '66 - Structured fitness opportunities',
    '67-exterior-active-design': '67 - Exterior active design',
    '68-physical-activity-spaces': '68 - Physical activity spaces',
    '69-active-transportation-support': '69 - Active transportation support',
    '70-fitness-equipment': '70 - Fitness equipment',
    '71-active-furnishings': '71 - Active furnishings',
    '72-accessible-design': '72 - Accessible design',
    '73-ergonomics: -visual-and-physical':
      '73 - Ergonomics:  visual and physical',
    '74-exterior-noise-intrusion': '74 - Exterior noise intrusion',
    '75-internally-generated-noise': '75 - Internally generated noise',
    '76-thermal-comfort': '76 - Thermal comfort',
    '77-olfactory-comfort': '77 - Olfactory comfort',
    '78-reverberation-time': '78 - Reverberation time',
    '79-sound-masking': '79 - Sound masking',
    '80-sound-reducing-surfaces': '80 - Sound reducing surfaces',
    '81-sound-barriers': '81 - Sound barriers',
    '82-individual-thermal-control': '82 - Individual thermal control',
    '83-radiant-thermal-comfort': '83 - Radiant thermal comfort',
    '84-health-and-wellness-awareness': '84 - Health and wellness awareness',
    '85-integrative-design': '85 - Integrative design',
    '86-postoccupancy-surveys': '86 - Post-occupancy surveys',
    '87-beauty-and-design-i': '87 - Beauty and design I',
    '88-biophilia-i-qualitative': '88 - Biophilia I - qualitative',
    '89-adaptable-spaces': '89 - Adaptable spaces',
    '90-healthy-sleep-policy': '90 - Healthy sleep policy',
    '91-business-travel': '91 - Business travel',
    '92-building-health-policy': '92 - Building health policy',
    '93-workplace-family-support': '93 - Workplace family support',
    '94-selfmonitoring': '94 - Self-monitoring',
    '95-stress-and-addiction-treatment': '95 - Stress and addiction treatment',
    '96-altruism': '96 - Altruism',
    '97-material-transparency': '97 - Material transparency',
    '98-organizational-transparency': '98 - Organizational transparency',
    '99-beauty-and-design-ii': '99 - Beauty and design II',
    '100-biophilia-ii-quantitative': '100 - Biophilia II - quantitative',
    '101-innovation-i': '101 - Innovation I',
    '102-innovation-ii': '102 - Innovation II',
    '103-innovation-iii': '103 - Innovation III',
    '104-innovation-iv': '104 - Innovation IV',
    '105-innovation-v': '105 - Innovation V',
    'p1-food-environment': 'P1 - Food environment',
    'p2-light-at-night': 'P2 - Light at night',
    'p3-circadian-emulation': 'P3 - Circadian emulation',
    'p4-impact-reducing-flooring': 'P4 - Impact reducing flooring',
    'p5-health-through-housing-equity': 'P5 - Health through housing equity',
    'p6-education-space-provisions': 'P6 - Education space provisions',
    'p7-strategic-dining-design': 'P7 - Strategic dining design',
    'p8-injury-prevention': 'P8 - Injury prevention',
    'p9-advanced-cleaning': 'P9 - Advanced cleaning',
  },
  staticWcsFeatures: {
    'smk-smoking-ban': 'SMK - Smoking Ban',
    'smo-outdoor-smoking-ban': 'SMO - Outdoor Smoking Ban',
    'lta-longterm-air-quality': 'LTA - Long-Term Air Quality',
    'lte-enhanced-longterm-air-quality': 'LTE - Enhanced Long-Term Air Quality',
    'sta-shortterm-air-quality': 'STA - Short-Term Air Quality',
    'ste-enhanced-shortterm-air-quality':
      'STE - Enhanced Short-Term Air Quality',
    'sep-pollution-source-separation': 'SEP - Pollution Source Separation',
    'prk-parking-restrictions': 'PRK - Parking Restrictions',
    'lev-low-emission-vehicles': 'LEV - Low Emission Vehicles',
    'aed-air-quality-education': 'AED - Air Quality Education',
    'wqt-drinking-water-quality': 'WQT - Drinking Water Quality',
    'wad-public-water-additives': 'WAD - Public Water Additives',
    'pwt-periodic-water-quality-testing':
      'PWT - Periodic Water Quality Testing',
    'wqo-high-quality-drinking-water': 'WQO - High Quality Drinking Water',
    'wac-drinking-water-access': 'WAC - Drinking Water Access',
    'fac-sanitary-facilities-provision': 'FAC - Sanitary Facilities Provision',
    'wfs-water-feature-sanitation': 'WFS - Water Feature Sanitation',
    'leg-legionella-control': 'LEG - Legionella Control',
    'swa-stormwater-management': 'SWA - Stormwater Management',
    'ovf-overflow-water-management': 'OVF - Overflow Water Management',
    'sup-supermarket-access': 'SUP - Supermarket Access',
    'fru-fruits-and-vegetables': 'FRU - Fruits and Vegetables',
    'hfo-healthy-food-procurement': 'HFO - Healthy Food Procurement',
    'fad-food-advertising': 'FAD - Food Advertising',
    'ned-nutrition-education': 'NED - Nutrition Education',
    'agr-urban-agriculture-i-–-provision':
      'AGR - Urban Agriculture I – Provision',
    'agp-urban-agriculture-ii-–-promotion':
      'AGP - Urban Agriculture II – Promotion',
    'faf-food-affordability': 'FAF - Food Affordability',
    'fse-food-security': 'FSE - Food Security',
    'fsa-public-food-inspection-information':
      'FSA - Public Food Inspection Information',
    'bre-breastfeeding-support': 'BRE - Breastfeeding Support',
    'lmp-lighting-master-plan': 'LMP - Lighting Master Plan',
    'lcs-lighting-control-schedule': 'LCS - Lighting Control Schedule',
    'emi-communitywide-emittance-caps': 'EMI - Community-Wide Emittance Caps',
    'lct-obtrusive-light-control': 'LCT - Obtrusive Light Control',
    'ltr-light-trespass-mitigation-for-sleep':
      'LTR - Light Trespass Mitigation for Sleep',
    'svi-visibility-facilitation': 'SVI - Visibility Facilitation',
    'rli-rightofway-lighting': 'RLI - Right-Of-Way Lighting',
    'lex-lighting-for-exteriors': 'LEX - Lighting for Exteriors',
    'mli-mass-transit-lighting': 'MLI - Mass Transit Lighting',
    'mix-mixeduse-development': 'MIX - Mixed-Use Development',
    'mnp-movement-network-planning': 'MNP - Movement Network Planning',
    'wak-walkability': 'WAK - Walkability',
    'ped-pedestrianscale-design': 'PED - Pedestrian-Scale Design',
    'pds-enhanced-pedestrian-environments':
      'PDS - Enhanced Pedestrian Environments',
    'cyc-cyclist-infrastructure': 'CYC - Cyclist Infrastructure',
    'bpk-bicycle-parking': 'BPK - Bicycle Parking',
    'cys-enhanced-cyclist-environments': 'CYS - Enhanced Cyclist Environments',
    'bsh-community-bicycle-share': 'BSH - Community Bicycle Share',
    'tra-mass-transit-infrastructure': 'TRA - Mass Transit Infrastructure',
    'trn-mass-transit-support': 'TRN - Mass Transit Support',
    'way-community-wayfinding': 'WAY - Community Wayfinding',
    'pas-physical-activity-spaces': 'PAS - Physical Activity Spaces',
    'prg-activity-programming': 'PRG - Activity Programming',
    'pet-pet-support': 'PET - Pet Support',
    'ext-extreme-weather-warnings': 'EXT - Extreme Weather Warnings',
    'het-urban-heat-adaptation: -community-support':
      'HET - Urban Heat Adaptation:  Community Support',
    'hpe-urban-heat-adaptation: -public-education':
      'HPE - Urban Heat Adaptation:  Public Education',
    'cld-urban-cold-adaptation: -community-support':
      'CLD - Urban Cold Adaptation:  Community Support',
    'cpe-urban-cold-adaptation: -public-education':
      'CPE - Urban Cold Adaptation:  Public Education',
    'him-urban-heat-island-mitigation': 'HIM - Urban Heat Island Mitigation',
    'veg-urban-vegetation-and-green-spaces':
      'VEG - Urban Vegetation and Green Spaces',
    'wat-urban-water-bodies': 'WAT - Urban Water Bodies',
    'sun-personal-sun-exposure': 'SUN - Personal Sun Exposure',
    'sou-sound-planning': 'SOU - Sound Planning',
    'smp-community-sound-mapping': 'SMP - Community Sound Mapping',
    'pln-planning-for-acoustics': 'PLN - Planning for Acoustics',
    'ord-noise-ordinance': 'ORD - Noise Ordinance',
    'nlv-noise-level-limit': 'NLV - Noise Level Limit',
    'hea-hearing-health-education': 'HEA - Hearing Health Education',
    'hwm-hazardous-waste-management': 'HWM - Hazardous Waste Management',
    'wst-waste-stream-management': 'WST - Waste Stream Management',
    'rem-site-remediation-and-redevelopment':
      'REM - Site Remediation and Redevelopment',
    'cre-construction-remediation': 'CRE - Construction Remediation',
    'ods-outdoor-structures': 'ODS - Outdoor Structures',
    'pes-landscaping-and-pesticide-use': 'PES - Landscaping and Pesticide Use',
    'haz-hazard-communication': 'HAZ - Hazard Communication',
    'amh-access-to-mental-health-services':
      'AMH - Access to Mental Health Services',
    'cri-mental-health-crisis-support': 'CRI - Mental Health Crisis Support',
    'abu-substance-abuse-and-addiction-services':
      'ABU - Substance Abuse and Addiction Services',
    'ark-substance-abuse-and-addiction-services-for-atrisk-populations':
      'ARK - Substance Abuse and Addiction Services for At-Risk Populations',
    'alc-alcohol-environment': 'ALC - Alcohol Environment',
    'rdr-responsible-driving': 'RDR - Responsible Driving',
    'ipv-support-for-victims-of-interpersonal-violence':
      'IPV - Support for Victims of Interpersonal Violence',
    'sgr-integration-of-streetscape-greenery':
      'SGR - Integration of Streetscape Greenery',
    'chi-outdoor-child-play-spaces': 'CHI - Outdoor Child Play Spaces',
    'gre-restorative-green-spaces': 'GRE - Restorative Green Spaces',
    'blu-restorative-blue-spaces': 'BLU - Restorative Blue Spaces',
    'blt-restorative-built-spaces': 'BLT - Restorative Built Spaces',
    'sce-preservation-of-scenic-views': 'SCE - Preservation of Scenic Views',
    'vis-community-visioning': 'VIS - Community Visioning',
    'hia-health-impact-assessment-screening':
      'HIA - Health Impact Assessment Screening',
    'hii-health-impact-assessment-implementation':
      'HII - Health Impact Assessment Implementation',
    'soc-social-spaces': 'SOC - Social Spaces',
    'pub-public-spaces': 'PUB - Public Spaces',
    'san-sanitation': 'SAN - Sanitation',
    'chw-community-health-and-wellness': 'CHW - Community Health and Wellness',
    'chr-community-health-resilience': 'CHR - Community Health Resilience',
    'pri-access-to-primary-healthcare': 'PRI - Access to Primary Healthcare',
    'edu-educational-opportunity': 'EDU - Educational Opportunity',
    'hou-fundamental-housing-quality': 'HOU - Fundamental Housing Quality',
    'equ-housing-equity-and-affordability':
      'EQU - Housing Equity and Affordability',
    'dig-digital-connectivity': 'DIG - Digital Connectivity',
    'eng-civic-engagement': 'ENG - Civic Engagement',
    'pre-preservation-and-rehabilitation':
      'PRE - Preservation and Rehabilitation',
    'cel-celebration-of-place': 'CEL - Celebration of Place',
    'art-public-art': 'ART - Public Art',
    'saf-community-confidence': 'SAF - Community Confidence',
    'poc-postoccupancy-surveys': 'POC - Post-Occupancy Surveys',
    'gnd-green-rating-systems': 'GND - Green Rating Systems',
    'inp-planning-for-health': 'INP - Planning for Health',
    'inv-innovate-well': 'INV - Innovate WELL',
    'wlp-well-accredited-professional': 'WLP - WELL Accredited Professional',
  },
})
