export default () => ({
  spaceTypes: null,
  adminProjectsList: null,
  project: null,
  accessLevel: null,
  estimate: null,
  projectInvoices: null,
  projectsList: null,
  strategies: null,
  projectDocuments: null,
  coachingContacts: null,
  wellReviewers: null,
  externalReviewers: null,
  ptAgents: null,
  pricingDetails: '',
  existingProjects: {},
  standards: null,
  directoryProjects: null,
  projectDirectoryFilters: null,
})
